name: build vischeck binaries

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: install pybind11
        run: pip install pybind11
      - name: build vischeck binaries
        shell: cmd
        run: |
          for /f "usebackq tokens=*" %%i in (`"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.Component.MSBuild -property installationPath`) do (
            call "%%i\Common7\Tools\VsDevCmd.bat"
          )

          msbuild VPhysToOpt.sln /p:Configuration=Release /p:Platform=x64

          :: get python include and lib dirs
          for /f "usebackq tokens=*" %%i in (`python -c "import sysconfig; print(sysconfig.get_path('include'))"`) do set PYTHON_INCLUDE=%%i
          for /f "usebackq tokens=*" %%i in (`python -c "import sysconfig; print(sysconfig.get_config_var('LIBDIR'))"`) do set PYTHON_LIB=%%i

          :: get pybind11 include path
          for /f "usebackq tokens=*" %%i in (`python -m pybind11 --includes`) do set PYBIND11_INCLUDES=%%i

          :: extract first include path from pybind11 output (-I"path" -I"other")
          for /f "tokens=1 delims=-I " %%a in ("%PYBIND11_INCLUDES%") do set PYBIND11_PATH=%%a
          set PYBIND11_PATH=%PYBIND11_PATH:"=%

          echo using python include: %PYTHON_INCLUDE%
          echo using python lib: %PYTHON_LIB%
          echo using pybind11 include: %PYBIND11_PATH%

          cl /LD /std:c++20 /I "%PYTHON_INCLUDE%" /I "%PYBIND11_PATH%" vischeck_module.cpp /link /LIBPATH:"%PYTHON_LIB%" /OUT:vischeck.pyd


      - name: upload built binaries
        uses: actions/upload-artifact@v4
        with:
          name: vischeck-win64
          path: |
            x64/Release/VPhysToOpt.exe
            VisCheckCS2\vischeck.pyd
