name: build vischeck binaries

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup vs dev environment + build
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\Tools\VsDevCmd.bat"
          msbuild VPhysToOpt.sln /p:Configuration=Release /p:Platform=Win32

      - name: upload VPhysToOpt.exe
        uses: actions/upload-artifact@v4
        with:
          name: vischeck-windows-binaries
          path: |
            Release/VPhysToOpt.exe
