name: build vischeck binaries

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: install pybind11
        run: pip install pybind11

      - name: locate vsdevcmd and build everything
        shell: cmd
        run: |
          :: locate visual studio
          for /f "usebackq tokens=*" %%i in (`"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.Component.MSBuild -property installationPath`) do (
            call "%%i\Common7\Tools\VsDevCmd.bat"
          )

          :: build VPhysToOpt.exe
          msbuild VPhysToOpt.sln /p:Configuration=Release /p:Platform=x64

          :: build vischeck.pyd manually
          cl /LD /std:c++20 /I "%PYTHON_INCLUDE%" /I "%USERPROFILE%\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\pybind11\\include" vischeck_module.cpp /link /LIBPATH:"%PYTHON_LIB%" /OUT:vischeck.pyd

      - name: upload built binaries
        uses: actions/upload-artifact@v4
        with:
          name: vischeck-win64
          path: |
            x64/Release/VPhysToOpt.exe
            vischeck.pyd
