name: build vischeck binaries

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: build VPhysToOpt with MSBuild
        run: |
          msbuild VPhysToOpt.sln /p:Configuration=Release /p:Platform=x64
        shell: cmd

      - name: upload VPhysToOpt.exe
        uses: actions/upload-artifact@v4
        with:
          name: vischeck-windows-binaries
          path: |
            x64/Release/VPhysToOpt.exe
